from __future__ import annotations

import argparse
from pathlib import Path


DEFAULT_ARRAY_NAME = "yes_no_model_quant_tflite"


def parse_args() -> argparse.Namespace:
    project_dir = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(description="Convert a .tflite model into C source files.")
    parser.add_argument(
        "--input",
        type=Path,
        default=project_dir / "yes_no_model_quant.tflite",
        help="Path to the input .tflite file.",
    )
    parser.add_argument(
        "--cc-output",
        type=Path,
        default=project_dir / "yes_no_model.cc",
        help="Path to the generated .cc file.",
    )
    parser.add_argument(
        "--header-output",
        type=Path,
        default=project_dir / "yes_no_model.h",
        help="Path to the generated .h file.",
    )
    parser.add_argument(
        "--array-name",
        default=DEFAULT_ARRAY_NAME,
        help="C symbol name for the generated byte array.",
    )
    return parser.parse_args()


def make_header(array_name: str) -> str:
    return f"""#ifndef YES_NO_MODEL_H_
#define YES_NO_MODEL_H_

extern unsigned char {array_name}[];
extern unsigned int {array_name}_len;

#endif  // YES_NO_MODEL_H_
"""


def make_cc(array_name: str, model_data: bytes) -> str:
    lines = []
    for offset in range(0, len(model_data), 12):
        chunk = model_data[offset : offset + 12]
        lines.append("  " + ", ".join(f"0x{value:02x}" for value in chunk) + ",")

    array_body = "\n".join(lines)
    return f"""#include "yes_no_model.h"

unsigned char {array_name}[] = {{
{array_body}
}};

unsigned int {array_name}_len = {len(model_data)};
"""


def main() -> None:
    args = parse_args()
    if not args.input.is_file():
        raise FileNotFoundError(f"Missing input model: {args.input}")

    model_data = args.input.read_bytes()
    args.header_output.write_text(make_header(args.array_name), encoding="utf-8")
    args.cc_output.write_text(make_cc(args.array_name, model_data), encoding="utf-8")

    print(f"Generated header: {args.header_output}")
    print(f"Generated source: {args.cc_output}")
    print(f"Bytes exported: {len(model_data)}")


if __name__ == "__main__":
    main()
